# Generated by Django 5.1.1 on 2024-11-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_post',
            name='available_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
