# Generated by Django 5.1.1 on 2024-11-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_post_available_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_post',
            name='available_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
