# Generated by Django 5.1.1 on 2024-11-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='number_of_posts',
            field=models.IntegerField(default=0),
        ),
    ]
