# Generated by Django 5.1.1 on 2024-11-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_number_of_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_post',
            old_name='event_title',
            new_name='event_post_title',
        ),
    ]
