# Generated by Django 5.1.1 on 2024-11-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_event_title_event_post_event_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_post',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
