# Generated by Django 5.1.1 on 2024-11-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_post',
            name='body',
        ),
    ]
