# Generated by Django 5.1.1 on 2024-11-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_event_post_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='event_post',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='event',
            name='event_pic',
            field=models.ImageField(blank=True, default='event_pics/default.png', upload_to='event_pics'),
        ),
    ]
